version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa-flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./actions:/app/actions
      - ./utils:/app/utils
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - rasa-network

networks:
  rasa-network:
    driver: bridge
